In [12]:
import torch
import numpy as np

In [9]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [8]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())

torch.Size([6])


In [11]:
v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)

tensor([1, 2, 3, 4, 5])


In [14]:
print(tensor_cnv.type())

torch.LongTensor


In [15]:
print(a)


[1 2 3 4 5]
