In [1]:
import torch

In [9]:
oneD = torch.arange(0, 9)
oneD

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
twoD = oneD.view(3,3)
twoD

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [11]:
twoD.dim()

2

In [12]:
x = torch.arange(18).view(2, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [13]:
x = torch.arange(18).view(3, 3, 2)
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])