In [1]:
import torch

In [2]:
x = torch.arange(18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [3]:
x[1][1][1]

tensor(10)

In [4]:
x[1]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [6]:
a = torch.tensor([1,2,3,4,5,6]).view(2,3)
b = torch.tensor([2,5,4,6,3,4]).view(3,2)
c = torch.matmul(a, b)
c

tensor([[19, 29],
        [46, 74]])

In [7]:
a @ b

tensor([[19, 29],
        [46, 74]])